# Documented at:
# https://github.com/shirakaba/expoot/wiki/questionnaire.toml-reference

expoot_schema_version = 1
react_native_version = "0.81"


# Comment out this section if you don't want to generate an Android app.
[android]
display_name = "example"
application_id = "com.expoot.example"


# Comment out this section if you don't want to generate an iOS app.
[ios]
bundle_display_name = "My Application"
bundle_identifier = "com.expoot.example"


# Comment out this section if you don't want to generate a macOS app.
[macos]
bundle_display_name = "My Application"
bundle_identifier = "com.expoot.example"


# Comment out this section if you don't want to generate a Windows app.
[windows]
namespace = "exampleapp"
display_name = "Example App"
publisher_display_name = "Example company"
project_name = "example.vcxproj"
root_namespace = "example.vcxproj"
entry_point_project_unique_name = "example.vcxproj"
