# Documented at:
# https://github.com/shirakaba/expoot/wiki/questionnaire.toml-reference

expoot_schema_version = 1
react_native_version = "0.81"

[name]
alphanumeric = "MyApp123"
display_name = "My App 123"
reverse_dns = "com.example.my-app-123"

[android]
# application_id = #name.reverse_dns
# package_namespace = #name.reverse_dns
# root_project_name = #name.display_name

[ios]
# bundle_identifier = #name.reverse_dns
# bundle_display_name = #name.display_name

[macos]
# bundle_identifier = #name.reverse_dns
# bundle_display_name = #name.display_name

[windows]
# display_name = #name.display_name
# namespace = #name.reverse_dns
# project_name = #name.alphanumeric
