name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - "packages/*/CHANGELOG.md"
      - "packages/expo-desktop-metro-config/*/CHANGELOG.md"
      - "templates/*/*/CHANGELOG.md"
  workflow_dispatch:

concurrency:
  group: publish-npm
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    # Matches the GitHub Environment name on each npm package’s "Trusted
    # publisher" config.
    environment: Stable Release
    permissions:
      # To push git tags
      contents: write
      # To publish to npm via OIDC
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/setup@v2
        with:
          version: latest
          cache: true
          install: false
          runtime: node@lts

      - name: Install dependencies
        run: >-
          pnpm install \
            --frozen-lockfile \
            --filter expo-desktop \
            --filter expo-desktop-config-plugins \
            --filter expo-desktop-metro-config \
            --filter expo-desktop-modules-core \
            --filter expo-desktop-prebuild-config \
            --filter expo-desktop-stubs \
            --filter custom-changeset

      # Build in order of dependency graph:
      # config-plugins → prebuild-config → expo-desktop.
      - name: Build expo-desktop and all of its dependents
        run: pnpm --filter expo-desktop... build

      - name: Publish packages
        id: changesets
        uses: changesets/action@v2
        with:
          version-script: node --run r2
          publish-script: node --run r3
